"""
Legacy: build a static Python dict from the SYNAPSE CSV.

Runtime matching now uses ``src/extraction/symptom_rag.py`` (CSV + word overlap)
instead of importing a huge generated file. You can still run this to inspect
or export phrases for other tools.

Usage (from repo root):
    python scripts/sync_synapse_lexicon.py
"""

from __future__ import annotations

import csv
import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "data" / "SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv"
OUT_PATH = REPO / "src" / "extraction" / "symptom_lexicon_synapse.py"

# Drop noise fragments from naive comma-splitting
_SKIP = frozenset(
    {
        "a",
        "an",
        "the",
        "and",
        "or",
        "of",
        "in",
        "on",
        "at",
        "to",
        "for",
        "with",
        "red",
        "white",
    }
)

# Known comma-split artifacts (not standalone symptoms in the dataset)
_BAD_KEYS = frozenset({"a white"})


def _normalize_key(phrase: str) -> str:
    return " ".join(phrase.lower().split())


def collect_phrases() -> dict[str, set[str]]:
    """canonical_key -> surface forms seen in the dataset."""
    by_key: dict[str, set[str]] = defaultdict(set)

    with CSV_PATH.open(newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        if "Symptoms" not in (reader.fieldnames or []):
            raise SystemExit(f"CSV missing Symptoms column: {reader.fieldnames}")

        for row in reader:
            raw = row.get("Symptoms") or ""
            for part in raw.split(","):
                s = part.strip()
                if not s:
                    continue
                key = _normalize_key(s)
                if len(key) < 2:
                    continue
                if key in _SKIP or key in _BAD_KEYS:
                    continue
                # Drop lone "a something" fragments that are usually split errors (keep if long enough)
                if len(key) <= 4 and key.startswith("a "):
                    continue
                by_key[key].add(s.strip())

    return by_key


def emit_python(by_key: dict[str, set[str]]) -> str:
    lines = [
        '"""',
        "Auto-generated by scripts/sync_synapse_lexicon.py — do not edit by hand.",
        f"Source: data/SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv",
        f"Entries: {len(by_key)} canonical symptom phrases from the dataset.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# canonical (lowercase) -> list of surface strings (for matching / display)",
        "SYNAPSE_SYMPTOM_EXTRA: dict[str, list[str]] = {",
    ]

    for key in sorted(by_key.keys()):
        variants = sorted(by_key[key], key=lambda x: (x.lower(), x))
        # Ensure lowercase canonical form is always a variation for substring matching
        if key not in {v.lower() for v in variants}:
            variants = [key] + variants
        lines.append(f"    {key!r}: {variants!r},")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not CSV_PATH.is_file():
        raise SystemExit(f"Missing CSV: {CSV_PATH}")

    by_key = collect_phrases()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = emit_python(by_key)
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {len(by_key)} entries to {OUT_PATH.relative_to(REPO)}")


if __name__ == "__main__":
    main()
